# Generated by Django 5.2.4 on 2025-08-30 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPetModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_imagem', models.ImageField(upload_to='fotos_pets/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('principal', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pets.petmodels')),
            ],
        ),
    ]
